### ISSUE TITLE
AttributeError: 'ReferenceSpaceApi' object has no attribute 'axes_order'

### ISSUE THREAD

**Issue by horsto** [brainglobe/brainrender#106]
When trying to render a scene, I run into the following (new) error: 
```
  File "~/python3.6/site-packages/bg_atlasapi/core.py", line 132, in hemispheres
    front_ax_idx = self.space.axes_order.index("frontal")
AttributeError: 'ReferenceSpaceApi' object has no attribute 'axes_order'
```

Complete error stack: 
```
Traceback (most recent call last):
 line 31, in <module>
    scene.add_actor_label(test, "l2", size=250, color="darkblue", zoffset=-7500, radius=None)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender/scene.py", line 525, in add_actor_label
    labels = make_actor_label(self.atlas, actors, labels, **kwargs)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender/Utils/scene_utils.py", line 172, in make_actor_label
    if atlas.hemisphere_from_coords(point, as_string=True) == "left":
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/bg_atlasapi/core.py", line 169, in hemisphere_from_coords
    hem = self.hemispheres[self._idx_from_coords(coords, microns)]
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/bg_atlasapi/core.py", line 132, in hemispheres
    front_ax_idx = self.space.axes_order.index("frontal")
AttributeError: 'ReferenceSpaceApi' object has no attribute 'axes_order'
```

**Comment by FedeClaudi** [comment]
Hi horsto, the line that gives you the error was introduced with 83e3403c4137a911f08dac644f3a558b7df70fd0 in the `dev` branch, am I correct in saying that you're using the `dev` branch?

Can you try getting the latest version from `dev` with: 
```
pip install -U git+https://github.com/BrancoLab/brainrender.git@dev
```
and see if the error persists? This code works fine for me:
``` python
# Create scene
scene = Scene(add_root=True, display_inset=True, title="Trasform + origin")

scene.add_sphere_at_point([5000, 2000, 3000])

scene.add_brain_regions('TH', 'CA1')
scene.render(camera='top')

```

**Comment by FedeClaudi** [comment]
Also for reference, I'm using `dev` to implement a few changes and new features: https://github.com/BrancoLab/brainrender/issues/104

As such there might be moments where the `dev` version doesn't work
Currently it doesn't work with the github version of `vedo` because I've been using a forked version until @marcomusy releases a version the latest additions, so you might get some errors (if that's the case I can point you towards the fork so that you can install `vedo` from there).

**Comment by horsto** [comment]
Thanks for the quick reply @FedeClaudi. So I tried both with `brainrender-1.0.0.1rc2` , and also with `brainrender-1.0.0.0`. The error persists and it seems to specifically occur when trying to add a 3D label: 

```
pas = scene.add_brain_regions(["PAR"], use_original_color=False, wireframe=True)
pas.c("lightblue").alpha(.4)
scene.add_actor_label(pas, "PAS", size=250, color="blackboard", zoffset=-200, radius=None)
```
-> this runs into an error at `scene.add_actor_label`, not before. Could you check that on your side?

**Comment by FedeClaudi** [comment]
sorry I didn't see in the error stack that that's what's causing the error, it's not related to what I said above then (i.e. it's not a brainrender issue)

Have you tried updating bg-atlaspi and bg-space (maybe installing from github's master branch) + updating your installed atlases?

**Comment by horsto** [comment]
Interesting. Ok, so I am on `bg-atlasapi-0.2.0` and `bg-space 0.5.0` and my atlas is `allen_mouse_10um (version: 1.1)` - does that match your setup?

**Comment by FedeClaudi** [comment]
Okay, no I've found the problem and it is indeed with brainrender.  
`brainrender.atlas.aba.ABA` overwrites the `.space` attribute which is used by bg-atlasapi already: 
https://github.com/BrancoLab/brainrender/blob/4c087bc4cb8f94ba394dc0cf75baa646065ea44b/brainrender/atlases/aba.py#L59

This means that when you try to add the label and `atlas.hemisphere_from_coords` is called, internally `bg-atlaspi`'s `BGAtlas` class uses `self.space` but this has now been overwritten, which is why you get `ReferenceSpaceApi` in the error. 
`ReferenceSpaceApi` is not from `bg-atlasapi` but it's part of the `allensdk` which is what `brainrender` replaces `atlas.space` with. 

Now, this issue has been fixed in `brainrender`'s dev branch (see 83e3403c4137a911f08dac644f3a558b7df70fd0), which you can get with:
```
pip install -U git+https://github.com/BrancoLab/brainrender.git@dev
```

however as I was saying at first it currently needs the forked version of `vedo` so you'll have to install that as well:
```
pip install -U git+https://github.com/FedeClaudi/vedo.git
```

Hope this solves things, and sorry about the confusion. `brainrender 1.0.0.2` will fix this for good (see https://github.com/BrancoLab/brainrender/issues/104) but I'm waiting for the next `vedo` release with the fixes I need.

**Comment by horsto** [comment]
Hey, no worries, thanks for checking. So this still doesn't quite work for me. With the pip installs you wrote about I am now on `vedo-2020.4.0` and `brainrender-1.0.0.1rc2` and the following error occurs: 
  ```
  scene.render()
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender/render.py", line 230, in render
    self._correct_axes()
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender/render.py", line 152, in _correct_axes
    actor.applyTransform(mtx).reverse()
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/vedo/pointcloud.py", line 2002, in applyTransform
    tf.SetTransform(transformation)
TypeError: SetTransform argument 1: method requires a VTK object
```

**Comment by horsto** [comment]
Thanks, works!

**Comment by rdbcasillas** [comment]
Hi @FedeClaudi , 

Is this issue supposed to be resolved with the latest brainrender 1.0.1.1? I am still getting the exact same error when I try to add labels. 

Thanks!

**Comment by FedeClaudi** [comment]
Hi,

Sorry can you copy the error stack that you're getting so that I know exactly which issue you're having?

Also can you double check that you're using the latest versions of brainrender, bg-space and bg-atlasapi please?

**Comment by FedeClaudi** [comment]
hey, 

as stated [in the docs](https://docs.brainrender.info/usage/using-notebooks) not all of brainrender's features are supported when embedding scenes into notebooks. Please consider either having the scene rendered in a pop-up window or not using the notebooks, in that case you'll have all features working.
