### ISSUE TITLE
ImportError: cannot import name 'iter_sections' from 'neurom.core'

### ISSUE THREAD

**Issue by damingli09** [brainglobe/brainrender#158]
Hi,

I am running into an issue of importing the package after successful installation. My python version is 3.7, and I installed brainrender via "pip install brainrender". Then I tried to use it by calling "from brainrender import Scene" in the terminal, it shows the following error:

from brainrender import Scene
Error in sys.excepthook:
Traceback (most recent call last):
  File "//anaconda3/envs/allensdk/lib/python3.7/site-packages/pyinspect/exceptions.py", line 146, in excepthook
    emanager.render_error()
  File "//anaconda3/envs/allensdk/lib/python3.7/site-packages/pyinspect/exceptions.py", line 83, in render_error
    relevant_only=self.relevant_only,
  File "//anaconda3/envs/allensdk/lib/python3.7/site-packages/pyinspect/_exceptions.py", line 291, in inspect_traceback
    eline = read_single_line(fpath, f.f_lineno - 1)
  File "//anaconda3/envs/allensdk/lib/python3.7/site-packages/pyinspect/utils.py", line 136, in read_single_line
    "When reading a single line from file: the file doesnt exist!"
FileExistsError: When reading a single line from file: the file doesnt exist!

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda3/envs/allensdk/lib/python3.7/site-packages/brainrender/__init__.py", line 12, in <module>
    from brainrender.scene import Scene
  File "//anaconda3/envs/allensdk/lib/python3.7/site-packages/brainrender/scene.py", line 19, in <module>
    from brainrender.actors import Volume
  File "//anaconda3/envs/allensdk/lib/python3.7/site-packages/brainrender/actors/__init__.py", line 3, in <module>
    from brainrender.actors.neurons import Neuron, make_neurons
  File "//anaconda3/envs/allensdk/lib/python3.7/site-packages/brainrender/actors/neurons.py", line 2, in <module>
    from morphapi.morphology.morphology import Neuron as MorphoNeuron
  File "//anaconda3/envs/allensdk/lib/python3.7/site-packages/morphapi/morphology/morphology.py", line 11, in <module>
    from neurom.core import iter_sections
ImportError: cannot import name 'iter_sections' from 'neurom.core' (//anaconda3/envs/allensdk/lib/python3.7/site-packages/neurom/core/__init__.py)

Thank you for your attention!

**Comment by FedeClaudi** [comment]
Hi,

Thanks for giving brainrender a shot. It seem that the issue might be with the version of `neurom` package. I have tested up to version `1.4.20` and it worked fine, which version are you using?

**Comment by damingli09** [comment]
Hi Federico,

Thanks for the info! I was using the latest version 2.1.0 of neurom. Now I downgraded it to 1.4.20 and it works. It seems that the new version is not compatible.

**Comment by FedeClaudi** [comment]
Hi, this seems unrelated to the original issue. What version of `vedo` and `vtk` are you running?

**Comment by sx18014** [comment]
Hi,

Thanks for the quick reply! I am running `vedo 2021.0.3` and `vtk 9.0.1`.

**Comment by FedeClaudi** [comment]
Hi,

It looks like the newer versions of `vedo` don't have the `offscreen` argument when calling the `show` function which creates the interactive rendering: https://github.com/marcomusy/vedo/blob/fd4f9aa58ac7739c61ff7bcf52bd6fcdd3443e3b/vedo/plotter.py#L1799

The simplest fix is to downgrade it with `pip install vedo==2021.0.2`, that should resolve the problem

**Comment by sx18014** [comment]
Hi,

Thanks a lot! It works well with `vedo 2021.0.2`.

**Comment by marcomusy** [comment]
@FedeClaudi Indeed this keyword was moved to the init of the `Plotter` class. So instead of 
```
plt = vedo.Plotter()
# ...
plt.show(offscreen=True)
```
you should have 
```python
plt = vedo.Plotter(offscreen=True)
# ...
plt.show()
```
